### Add New User

POST http://localhost:5000/user
Content-Type: application/json

{
  "name": "Ahmed hany",
  "email": "ah40@gmail.com",
  "password": "12345678"
}


### Add Multiple Users

POST http://localhost:4000/user/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjksImVtYWlsIjoiYWhAZ21haWwuY29tIiwiaWF0IjoxNzM1NTk3ODc2LCJleHAiOjE3MzY1OTc4NzYsImF1ZCI6ImxvY2FsaG9zdDo0MDAwIiwiaXNzIjoibG9jYWxob3N0OjQwMDAifQ.zCHh6PAo8tfawAyLV-TOG1dXnofUPv7wOscnAXwQ3AY

{
  "users": [
    {
      "name": "test transaction 1",
      "email": "tansaction5@gmail.com",
      "password": "123456789"
    },
    {
      "name": "test transaction 2",
      "email": "tansaction6@gmail.com",
      "password": "123456789"
    }
  ]
}