### Create Post

POST http://localhost:6000/post
Content-Type: application/json

{
  "title": "test bidirectional",
  "content": "test bidirectional",
  "slug": "test-bidirectional",
  "postType": "post",
  "status": "published",
  "imageUrls": "https://example.com/image.jpg",
  "schema": "{\r\n \"type\": \"object\",\r\n  \"properties\": {\r\n    \"name\": {\r\n      \"type\": \"string\"\r\n    },\r\n    \"age\": {\r\n      \"type\": \"number\"\r\n    }\r\n  }\r\n}",
  "metaOptions": {
    "value": "{\"sideBarEnable\": \"true\", \"sideBarTheme\": \"dark\", \"topBarTheme\": \"light\"}"
  },
  "publishedAt": "2021-09-01T00:00:00.000Z",
  "authorId": 1
}